### ISSUE TITLE
Modded ore blocks crash

### ISSUE THREAD

**Issue by bondgb** [MinecraftModDevelopment/OreSpawn#1]
I'm getting this error in FML-client-latest.log

Description: Failed reading config gentle.json

java.lang.RuntimeException: Invalid state ore=niter for block minecraft:air

gentle.json:

[
  {
    "dimension": -1,
    "ores": [
      {
        "block": "minecraft:quartz_ore",
        "size": 15,
        "variation": 4,
        "frequency": 7,
        "min_height": 0,
        "max_height": 128
      },
      {
        "block": "substratum:ore",
        "state": "ore=niter",
        "size": 7,
        "variation": 4,
        "frequency": 4,
        "min_height": 0,
        "max_height": 128
      },
      {
        "block": "substratum:ore",
        "state": "ore=sulfur",
        "size": 7,
        "variation": 4,
        "frequency": 4,
        "min_height": 0,
        "max_height": 128
      }
    ]
  },
  {
    "ores": [
      {
        "block": "minecraft:clay",
        "size": 22,
        "variation": 12,
        "frequency": 5,
        "min_height": 0,
        "max_height": 64
      },
      {
        "block": "minecraft:obsidian",
        "size": 4,
        "variation": 2,
        "frequency": 1,
        "min_height": 16,
        "max_height": 24
      },
      {
        "block": "minecraft:stone",
        "state": "variant=andesite",
        "size": 30,
        "variation": 10,
        "frequency": 10,
        "min_height": 0,
        "max_height": 80
      },
      {
        "block": "minecraft:stone",
        "state": "variant=diorite",
        "size": 30,
        "variation": 50,
        "frequency": 10,
        "min_height": 0,
        "max_height": 80
      },
      {
        "block": "minecraft:stone",
        "state": "variant=granite",
        "size": 30,
        "variation": 10,
        "frequency": 10,
        "min_height": 0,
        "max_height": 80
      },
      {
        "block": "minecraft:coal_ore",
        "size": 22,
        "variation": 15,
        "frequency": 15,
        "min_height": 4,
        "max_height": 128
      },
      {
        "block": "minecraft:iron_ore",
        "size": 14,
        "variation": 10,
        "frequency": 10,
        "min_height": 0,
        "max_height": 64
      },
      {
        "block": "minecraft:gold_ore",
        "size": 16,
        "variation": 13,
        "frequency": 4,
        "min_height": 0,
        "max_height": 37
      },
      {
        "block": "minecraft:redstone_ore",
        "size": 16,
        "variation": 8,
        "frequency": 8,
        "min_height": 0,
        "max_height": 24
      },
      {
        "block": "minecraft:lapis_ore",
        "size": 22,
        "variation": 18,
        "frequency": 2,
        "min_height": 0,
        "max_height": 32
      },
      {
        "block": "minecraft:emerald_ore",
        "size": 8,
        "variation": 4,
        "frequency": 2,
        "min_height": 0,
        "max_height": 21
      },
      {
        "block": "minecraft:diamond_ore",
        "size": 11,
        "variation": 5,
        "frequency": 2,
        "min_height": 0,
        "max_height": 23
      },
      {
        "block": "substratum:ore",
        "state":"ore=copper",
        "size": 11,
        "variation": 7,
        "frequency": 6,
        "min_height": 20,
        "max_height": 50
      },
      {
        "block": "substratum:ore",
        "state":"ore=tin",
        "size": 7,
        "variation": 4,
        "frequency": 5,
        "min_height": 16,
        "max_height": 52
      },
      {
        "block": "substratum:ore",
        "state":"ore=nickel",
        "size": 14,
        "variation": 10,
        "frequency": 5,
        "min_height": 0,
        "max_height": 36
      },
      {
        "block": "substratum:ore",
        "state":"ore=silver",
        "size": 14,
        "variation": 7,
        "frequency": 5,
        "min_height": 0,
        "max_height": 42
      },
      {
        "block": "substratum:ore",
        "state":"ore=lead",
        "size": 7,
        "variation": 5,
        "frequency": 6,
        "min_height": 16,
        "max_height": 48
      },
      {
        "block": "substratum:ore",
        "state":"ore=platinum",
        "size": 5,
        "variation": 2,
        "frequency": 3,
        "min_height": 20,
        "max_height": 60
      },
      {
        "block": "tile.techreborn.ore",
        "state":"type=iridium",
        "size": 5,
        "variation": 3,
        "frequency": 4,
        "min_height": 15,
        "max_height": 30
      },
      {
        "block": "immersiveengineering:ore",
        "state": "type=aluminum",
        "size": 16,
        "variation": 10,
        "frequency": 6,
        "min_height": 16,
        "max_height": 40
      },
      {
        "block": "bigreactors:brOre",
        "size": 16,
        "variation": 10,
        "frequency": 16,
        "min_height": 16,
        "max_height": 50,
        "biomes": [
          "biomesoplenty:dead_forest",
          "biomesoplenty:dead_swamp",
          "biomesoplenty:wasteland"
        ]
      },
      {
        "block": "biomesoplenty:biome_block",
        "size": 1,
        "variation": 5,
        "frequency": 1,
        "min_height": 16,
        "max_height": 50
      }
    ]
  }
]

Looks like it doesn't recognize the block? 

Using Forge 2075, MMD OreSpawn 2.0.0.3

**Comment by iLexiconn** [comment]
Fixed in 2.0.0.4, will release somewhere today.

**Comment by bondgb** [comment]
Same error on 2.0.0.4

**Comment by iLexiconn** [comment]
Then you aren't using the right id/don't have the mod installed. It works fine for me.

**Comment by psychofad** [comment]
correct me if I am wrong but shouldn't

```
{
"block": "substratum:ore",
"state": "ore=niter",
"size": 7,
"variation": 4,
"frequency": 4,
"min_height": 0,
"max_height": 128
},
```

actually be:

```
{
"block": "substratum:ore",
"state": "variant=niter",
"size": 7,
"variation": 4,
"frequency": 4,
"min_height": 0,
"max_height": 128
},
```

**Comment by bondgb** [comment]
FYI it's probably because it should be varaints=ore=niter, your parser chokes on the second '='.

**Comment by bondgb** [comment]
No. FYI it's probably because it should be variants=ore=niter, your parser chokes on the second '='.
