### ISSUE TITLE
1.12 | OreSpawn3 | Adding more materials

### ISSUE THREAD

**Issue by TheSpicePhantom** [MinecraftModDevelopment/OreSpawn#102]
Hello everyone!
I got some problems with the json structure, i mean, i can modify things just fine but adding is impossible.

Mods used:
See current MMD Public Pack.
orespawn3 1.12 - 3.2.0.95

OS:
For whatever reason 😄 Windows 10

More info:
If you load up a new world with the config i added, Basalt will not generate in any desert or mesa biome, whereas Inferium and Prosperity Shards will generate (without specified settings? Above, between and below min and max height.). Too i can't specify metaData.

I'm adding my current file to show you what i'm trying to do.
[To pastebin we go](https://pastebin.com/CEqnAJV6)

**Comment by dshadowwolf** [comment]
hrm,,, blargh - I really need to write some docs, as working on the 1.1 format of the JSON is... difficult for me.  The newest format - "version": "2.0" - is better in all respects, but I've not yet documented it fully.

**Comment by dshadowwolf** [comment]
Solved this around 0030 January 8 - was a multi-layered issue dating to some code that wasn't given as much of a stress-test as was needed. Should be working in the version on the Maven.
