### ISSUE TITLE
Block updates on air/fluid

### ISSUE THREAD

**Issue by Shovinus** [MinecraftModDevelopment/OreSpawn#103]
When replacing a solid block with a fluid/air  or when placing an air/fluid block the block needs to do a block update to make possible fluids flow/flowers pop off

**Comment by dshadowwolf** [comment]
This has been done in the past and caused problems with "cascading chunk-gen lag" being induced because of the block update spreading into unloaded chunks and causing them to load and generate. There is no middle ground, sadly.

**Comment by dshadowwolf** [comment]
have reversed this decision as part of making sure that we are not creating issues with other mods.
