### ISSUE TITLE
None of the mod's ores will spawn in new worlds

### ISSUE THREAD

**Issue by IndigoAvemour** [MinecraftModDevelopment/OreSpawn#109]
I use the most recent versions of MMD, BaseMetals, and ModernMetals on 1.12.2. Upon updating to the most recent version of this mod, new worlds will no longer generated any ores from the aforementioned mods. Rolling back to the previous version fixes things.

**Comment by dshadowwolf** [comment]
Since this was posted there have been some major updates. A proper test will require the removal of the OreSpawn config directory (at <minecraft instance>/config/orespawn3) so that no configuration data from prior versions is hanging around causing issues.

**Comment by dshadowwolf** [comment]
Closing due to lack of response from tester and age of issue
