### ISSUE TITLE
Meta Data Format

### ISSUE THREAD

**Issue by 99Blocks** [MinecraftModDevelopment/OreSpawn#110]
Sorry to ask what is probably an obvious question but I am having trouble with meta data for ore spawning and I wanted to check the syntax for the mod.

I am using version "3.2.1.109" and currently all my ores are set up like this:

        {
          "block": "chisel:limestone2",
          "blockMeta": "7",
          "parameters": {
            "size": 64,
            "variation": 2,
            "frequency": 12.0,
            "minHeight": 0,
            "maxHeight": 256
          },
            "feature": "default",
            "replace_block": "default",
            "biomes": []
        },

However it is not reading the meta correctly and I can't seem to find the correct syntax for implementing that in world gen.

Any assistance would be massively appreciated!

**Comment by dshadowwolf** [comment]
And... due to some issues I seem to have introduced, that will not work - that appears to be a "version": 1 format and support for that was broken (unintentionally, as *Metals uses the 1.1 variant) with the 3.2 release.

A sample (your above item) in the latest format:
```json
{
  "version": "2.0",
  "spawns": {
    "chiseled limestone, set 2 variant 7": {
      "blocks": [ { "name": "chisel:limestone2", "state":"variant=7", "chance": 100 } ],
      "parameters": {
        "size": 64,
        "variation": 2,
        "frequency": 12.0,
        "minHeight": 0,
        "maxHeight": 256
      },
      "feature": "default",
      "replace_block": "default",
      "biomes": {
        "excludes": []
      }
    }
  }
}
```

Recent release of any of the various "Metals" mods should have more examples of this format.

**Comment by 99Blocks** [comment]
Thanks for the quick response!

My current config file says "version": "1.1"
Can I manually change it in the config or does it require an update of some kind?

I have checked that I am running the most recent version of the "Release" mod, if there is an alpha version with these changes just let me know.

**Comment by dshadowwolf** [comment]
The example I've given above is for the newest format - one of the features of the existing code is it will not replace existing files. But also, in the 3.2 series, there is a file that tracks what mods have had their configs already extracted from the jar. Both of these features exist so you can remove or replace the defaults with your own and not have to worry about your custom configs being replaced.

**Comment by dshadowwolf** [comment]
Some documentation is on the Github Wiki for this project, more is coming. Closing this issue as "resolved"
