### ISSUE TITLE
Add a command to create a JSON object for the block in your hand

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MinecraftModDevelopment/OreSpawn#12]
For someone inexperienced in JSON or this mod, creating a functional JSON object to get a block to spawn can be quite challenging. I'd like to recommend that a command be added that creates a properly structured object and adds it to the specified orespawn file.

The command would be structured like this:

`/addore [name of file] <allfields>`

Example command:

`/addore minecraft.json allfields`

If the [name of file] field is not specified, it will default to the first file it finds, generally the one created by the mod on startup.

Upon creation, the object would have the same values as coal. Because coal is common, it would be easy to notice that it is generating properly. The specifics of how it spawns can be tweaked by the end user, this command just generates a working file.

The <allfields> thing is optional. If it's included in the command, all optional fields will be generated. Extra fields include "state" and "biomes" as well as any other fields that I'm not aware exist. These will be empty, and it will be up to the end user to decide which ones to keep and which ones to add extra detail to.

**Comment by iLexiconn** [comment]
https://minecraft.curseforge.com/projects/mmd-orespawn/files/2350329
`/addore <file> <dimension|all>`

**Comment by Kuktar** [comment]
i can not figure out how to use the addore command,. it just tells me it dosent exist...

**Comment by Kuktar** [comment]
omg i am on version 1.1.0 wich is missing all the cool new features. Can someone call FTB and tell them to put the updated one inside there latest ftb infinity lite 1.10.2 pack, kthnx. Seriously v2 ore spawner is so much better. GREAT JOBB MMD
