### ISSUE TITLE
Any estimate on Dimension Blacklist/Whitelist feature?

### ISSUE THREAD

**Issue by Boolyman** [MinecraftModDevelopment/OreSpawn#121]
Hello there, I have a big pack coming out in a few weeks, and I need to implement an ore spawning solution.  I need this solution to be able to whitelist and blacklist dimensions, which according to your wiki is not available yet... but soon.  Would you mind at least telling me if its reasonable to wait for this feature in the very near future (week or two), or if I should look at a different ore generation mod?

**Comment by dshadowwolf** [comment]
Being worked on as part of a comprehensive cleanup and simplification of the binary api and the json handling code. As it stands the attempt to maintain compat with the pre-3.2 cofigs (tagged as "version": "2.0" in the json) created a number of bad regressions and impossible to fix bugs - unless this rework is done. I cannot state that a week will see it reach as stable a state as it should be, but I am aiming to have at least a beta of 3.3 with the rework out within 8 days, end of the month for sure.

**Comment by dshadowwolf** [comment]
Over on [my fork](https://github.com/dshadowwolf/OreSpawn/tree/new-api )  of the repo, in the branch I've linked to there, you'll find the current progress. It doesn't build (yet) but I'm about 80% done with the work of updating things. The only issue, at this point, is that I have completely removed support for anything but the "version": "2.0" config files.

But OreSpawn 3.3 should be done well before the end of the month and be available as a -dev version for some testing before we release it to CurseForge.

**Comment by dshadowwolf** [comment]
There is, now, (0120 EST, 28-MAR-2018) no more than eight hours of work left before OreSpawn 3.3.0 will be "matching 3.2.2 for all important functionality" (I have removed all backwards compatibility with the OreSpawn 3, version 1.x configs, as that and the compat with OreSpawn 1 and OreSpawn 2 configs was causing a lot of the bugs)

Hopefully there will be sufficient testing for at least a Beta of it to be released onto CurseForge within 12 hours of the work being completed.

**Comment by dshadowwolf** [comment]
PR #122 should solve this - it has not been given a thorough test, yet, but the Biome blacklist/whitelist code - which worked once some bug fixes went in - was used as a basis for the design and it should work just as well.

Will close this when there is a bit more testing.

**Comment by dshadowwolf** [comment]
PR #123 cleans up the code even more, fixes the last of the major, outstanding bugs and is just waiting on @jriwanek to review and accept. It should, in all honesty, make CurseForge sometime today or early on Friday.

Back up <minecraft>/config/orespawn3 then delete it so that some internal changes in OreSpawn have a chance to create the files needed (you'll find that the various "*-default.json" files in the "sysconf" directory are gone, replaced by "*-orespawn.json" ones). This change was done to finally implement the "replacements file" and to move all definition of items from code to data.

**Comment by dshadowwolf** [comment]
It took an extra day thanks to finding that the "tries to spawn stuff that doesn't exist" bug still existed even though I'd thought it had been fixed.

Version 3.3.0 is now available on CurseForge and should resolve all the issues, including the Biome and Dimension whitelist and blacklist issues.

**Comment by dshadowwolf** [comment]
Available on CurseForge now for 1.12.2
