### ISSUE TITLE
ServerSide - Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MinecraftModDevelopment/OreSpawn#126]
https://gist.github.com/P3rf3ctXZer0/60d212ce68cb5041c60bf54b482f380b

**Comment by dshadowwolf** [comment]
...
You upgraded without removing existing configs... Let me go edit the CF page to make it clear - upgrading to 3.3.0 requires removing, at a minimum, 2 files from the orespawn3/sysconf directory and a line from orespawn3/sysconf/known-configs.json - there are some format differences.
