### ISSUE TITLE
Add a command to generate a list of all registered biomes

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MinecraftModDevelopment/OreSpawn#13]
OreSpawn gives users the option of specifying which biomes to generate ores in. This is specified with the following field:

`        "biomes": [`

`          "minecraft:extreme_hills",`

 `         "minecraft:smaller_extreme_hills"`

 `       ]`

However, it's tricky to know which biomes exist. I'd like to recommend that a command be added to create a text file in the minecraft root directory that includes a list of all registered biomes.

**Comment by iLexiconn** [comment]
https://minecraft.curseforge.com/projects/mmd-orespawn/files/2350329
`/dumpbiomes`
