### ISSUE TITLE
Crash's After Updating Forge Version

### ISSUE THREAD

**Issue by jopejoe1** [MinecraftModDevelopment/OreSpawn#132]
Crash Report: https://pastebin.com/dk26kMCy
After Updating Forge to the newst Version Minecraft crashes.
Without this mod and the mods that dependant on it its not crashing when i put it ihn again it crashes.

**Comment by dshadowwolf** [comment]
Not OreSpawn. BaseMetals. Known issue there - CoFHCore had a breaking API change. Thermal Expansion 5.4.2 has full support for BaseMetals, NetherMetals and EndMetals in the current release. In the BaseMetals config set the option for the Thermal Expansion integration to "false".
