### ISSUE TITLE
[build 136] Server crash (NoSuchElementException)

### ISSUE THREAD

**Issue by Geethebluesky** [MinecraftModDevelopment/OreSpawn#134]
[Crash log](https://pastebin.com/9VVGhJCm)

This happened specifically when I triggered the mod to retrogen via Speiger's Chunk Pregenerator to add ores to my existing chunks, **not** when the server is running normally (playing normally)--I haven't run into any 100% new chunks at this time so I don't know if it would happen then.

**Edit:** Ok, well just randomly walking around (no chunk generator running), I received the same type of crash, here's the [log ](https://pastebin.com/xyPP74L2)for that one.

I guess the chunkgen above is a good way of triggering it whenever, though.

**Comment by dshadowwolf** [comment]
I'm not 100% positive, but it appears as though the code is trying to run an event handler that should only be conditionally registered. In OreSpawn the "world tick" event is only bothered with if OreSpawn itself is doing retrogen... However, the second crash looks exactly the same and seems... hrm... I wonder if I'm missing a check for the list of things to be generated being empty...

Good report, I'll have to poke at this and am wondering exactly why I've not run into this in testing
