### ISSUE TITLE
Desync between client and server due to bad logic, attached log section

### ISSUE THREAD

**Issue by assasing123** [MinecraftModDevelopment/OreSpawn#135]
![desync](https://user-images.githubusercontent.com/9137556/42011831-91dacbca-7a52-11e8-943f-d59d75a83178.jpg)
![desync0](https://user-images.githubusercontent.com/9137556/42011832-91fbb68c-7a52-11e8-899a-04ef58362b34.png)

**Comment by dshadowwolf** [comment]
Should be fixed in -dev
