### ISSUE TITLE
[Crash] Crash on initialization (java.lang.IllegalStateException: This is not a JSON Array)

### ISSUE THREAD

**Issue by CactusDuud** [MinecraftModDevelopment/OreSpawn#140]
https://paste.dimdev.org/gozixogoye.mccrash

No idea what happened

**Comment by dshadowwolf** [comment]
Crash report doesn't line up with code base - this does look, however, like an issue with the "known-configs" file (<instance>/config/orespawn3/sysconf/known-configs.json) not being the correct format.

**Comment by dshadowwolf** [comment]
Okay, managed to get back to before one of the regular code-cleanups that managed to add some extra lines and... It is exactly what I thought - the "known configs" file is supposed to start with a [ and end with a ] - that is not what you have, at all. Add those to the file.

**Comment by dshadowwolf** [comment]
resolved as incorrect format in user-modified/created version of a nominally generated file
