### ISSUE TITLE
OreSpawn 3.3.0.153 causes error spam with Galacticraft

### ISSUE THREAD

**Issue by brisingraerowing** [MinecraftModDevelopment/OreSpawn#141]
[Log File](https://gist.github.com/BrisingrAerowing/9fc330550bcd48224896cb615245f124)

Major error spam with Galacticraft. Something about generating ores.

**Comment by dshadowwolf** [comment]
Actually a known issue - have a fix in the pipeline. The current release has a logic bug where it would properly parse the configs but not properly create the data structures used later. Had Galacticraft not taken over this would have resulted in minecraft crashing.

**Comment by dshadowwolf** [comment]
Closing as resolved
