### ISSUE TITLE
Cascading Worldgen Lag

### ISSUE THREAD

**Issue by Keaft** [MinecraftModDevelopment/OreSpawn#144]
`OreSpawn loaded a new chunk [1, 2] in dimension 0 (overworld) while populating chunk [2, 2], causing cascading worldgen lag.`

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

Essentially, probably a good idea to make the ore spawning happen snapping to the 16x16 grid and not cross over to another chunk causing it to load as well.

Edit: having another read through that reddit link, it talks about having a +8, +8 block buffer to ensure it "decoration" doesn't spill over into a new chunk.

**Comment by dshadowwolf** [comment]
We do this and it has never helped. Every place this occurs is where we have a spawn next to a fluid, which causes the fluid to update and cascade across.

So... Kindly, fuck off.
