### ISSUE TITLE
"Minecraft couldn't keep up"

### ISSUE THREAD

**Issue by Thesmartone7** [MinecraftModDevelopment/OreSpawn#149]
so ever sense i installed this mod i've had some huge cascading world lag issues, causing me to load forever as minecraft "can't keep up" id give a crash report but it doesn't exactly crash, i can still sort of move just nothing updates and there is no interaction, attempting to quit the game causes a crash, but one that only logs up to the moment that the issue happened, then it just cuts off, cascading world gen lag is always there, if in case this isn't your mod doing this i'm sorry, it has simply happened far too much and i seem to be unable to fix it.

**Comment by dshadowwolf** [comment]
...well, shit - Give me a bit, it seems that we have this somewhat fixed, but not released. My bad.

**Comment by dshadowwolf** [comment]
There, pushed 3.3.1 - let me know if that resolves the issue

**Comment by Thesmartone7** [comment]
While it still happens it is simply cause i have a lot of demanding mods, this fix of yours has helped a lot, minecraft is playable again, Thank you very much.
