### ISSUE TITLE
Server Hang Watchdog Crash 

### ISSUE THREAD

**Issue by jusitnboggs** [MinecraftModDevelopment/OreSpawn#160]
Server crashes let me know if you need any more info.

Crash report
https://pastebin.com/MiFe8y7s

**Comment by dshadowwolf** [comment]
ffffff

This looks similar to a few others I that were reported and that I ran into when testing before the release of the current version (I think) - let me double check, it might be that we need to just release...

**Comment by jusitnboggs** [comment]
I suppose I should also note that I am using version 1.0.0-rc1.28 because when I use the lastest I crash speaking of which I should report that crash log too while I'm here.

**Comment by dshadowwolf** [comment]
ah! Well... doesn't matter - this is still a bug and one I thought squashed, if I'm right

**Comment by dshadowwolf** [comment]
should have been fixed by #164 - closing.
