### ISSUE TITLE
[Suggestion] Please consider the following, as soon as possible 

### ISSUE THREAD

**Issue by MysticAura** [MinecraftModDevelopment/OreSpawn#17]
1. More complete documentation.
2. Allow any block in game (mod or otherwise) to be put into gen. Currently it only works with vanilla blocks. The others are ignored.
3. If there's a way to make + dimension modifier also allow an exception (the end) it would make json files much smaller. Seems like the only way I'll be able to make sure the end doesn't fill with overworld things, is by writing a different section for every single positive dimension.

This mod could be invaluable to mod pack devs if this kind of freedom was implemented.

**Comment by iLexiconn** [comment]
Don't combine issues, please

**Comment by dshadowwolf** [comment]
1.  When time can be found documentation of the commands and the format of the json files for OreSpawn 3 and any of the "special" json files it also uses will be created. (or if I can find someone that can do it for me)
2. At current the system is reading and registering its configs during the "Pre Init" phase of startup. If it would help, it should be possible to change it to later - perhaps as late as the "Post Init" phase of startup or even into the "Server Starting" phase. This decision will require some discussion among the team to decide on the best path. (Adding this to the potential upgrades list)
3. OreSpawn 3 has the "wildcard" specifically exclude "The End" and "The Nether".

**Comment by dshadowwolf** [comment]
1. See the Wiki, specifically [the OreSpawn 3 JSON documentation](/MinecraftModDevelopmentMods/OreSpawn/wiki/OreSpawn-3-JSON-Documentation) which gives a good overview and explanation of the current JSON format implemented by the upcoming OreSpawn 3 release.

**Comment by dshadowwolf** [comment]
item #3 on your list is the next item on my TODO - making a full whitelist/blacklist for dimension data.

**Comment by dshadowwolf** [comment]
OreSpawn 3.2 has all of these features. Closing this issue.
