### ISSUE TITLE
[1.10.2] Modern Metals ores aren't spawning

### ISSUE THREAD

**Issue by DanielKled** [MinecraftModDevelopment/OreSpawn#173]
Modern Metals ores don't spawn, but Base Metals do.

**Comment by jriwanek** [comment]
Upload game logs to a site like pastebin, then link them here, we can't help with no information.

Other questions we also need answers to:
1) What minecraft launcher are you using?
2) What site did you download our mods from?

**Comment by jriwanek** [comment]
As you've not responded, we can only assume that you're either a pirate user, or that you used a repost site, in either case, we don't provide support for that, so as tests demonstrate that your issue doesn't occur in official builds, your issue will be closed.
