### ISSUE TITLE
Block variants are not being accepted

### ISSUE THREAD

**Issue by TerdyTheTerd** [MinecraftModDevelopment/OreSpawn#175]
I took the example config from the config after my configs did not work, and the black variants are not accepted as valid
`[22:05:38] [Client thread/ERROR] [orespawn]: Exception: variant is not a known property of ic2:resource
com.mcmoddev.orespawn.util.StateUtil.deserializeState (StateUtil.java:49)
com.mcmoddev.orespawn.impl.os3.BlockBuilder.setFromNameWithChance (BlockBuilder.java:153)
com.mcmoddev.orespawn.impl.os3.BlockBuilder.setFromNameWithChance (BlockBuilder.java:126)
com.mcmoddev.orespawn.json.OreSpawnReader.loadBlocks (OreSpawnReader.java:252)
com.mcmoddev.orespawn.json.OreSpawnReader.loadSingleEntry (OreSpawnReader.java:215)
com.mcmoddev.orespawn.json.OreSpawnReader.lambda$tryReadFile$0 (OreSpawnReader.java:107)
com.mcmoddev.orespawn.json.OreSpawnReader$$Lambda$1569/2123390800.accept (null:-1)
j`
This is using the example config from the wiki...
`,
		"ic2 copper": {
			"retrogen": false,
			"enabled": true,
			"dimensions": [],
			"biomes": { "excludes": [] },
			"blocks": [ { "name": "ic2:resource", "state": "variant=1", "chance": 100 } ],
			"replaces": "default",
			"feature": "clusters",
			"parameters": {
				"minHeight": 32,
				"maxHeight": 96,
				"minAttempts": 4,
				"maxAttempts": 12,
				"maxSpread": 16,
				"size": 8,
				"numObjects": 16,
				"variation": 8
			}
		}`

This results in worlds not loading, just freezing on an empty client screen, never proceeding to rendering anything as the generator presumably gets frozen. How can I use block variants for ores since the example doesn't work

**Comment by dshadowwolf** [comment]
hrm... Give me a day or two to get free of paid-work concerns and to poke at this, please. It seems like there is a bug where the state serialize/deserialize does not "gracefully degrade" or handle an error properly...

**Comment by dshadowwolf** [comment]
Taking a look it appears your syntax is incorrect - it appears that IC2 would use something like `type=copper_ore` and not `variant=1`. Please try the `/addore` command we provide to get the data.

**Comment by TerdyTheTerd** [comment]
Not to poke at closed tickets, but how can this be user-error when I used the config from the mods wiki...either the wiki is incorrect or the mod isn't functioning properly.

**Comment by dshadowwolf** [comment]
IC2 has a different property syntax. The error is rather clear - `variant` is not correct for IC2's items. 

`[22:05:38] [Client thread/ERROR] [orespawn]: Exception: variant is not a known property of ic2:resource `

If memory serves the example in the Wiki was created back around 1.10 and never actually tested. If it's incorrect, it's incorrect - it was meant as an example, not something for people to directly use. As I noted in a previous response, the correction would be to replace the `state` entry with a correct one. I even went and checked, the correct data for it would be `"type=copper_ore"`.

**Comment by jriwanek** [comment]
And for clarity, we've put specific entries on the wiki pages.
