### ISSUE TITLE
Mesa Biomes Override

### ISSUE THREAD

**Issue by MrAmericanMike** [MinecraftModDevelopment/OreSpawn#18]
I have a question, I believe it's since 1.10 that Mesa Biomes in Minecraft spawn extra gold ores.

Does the mod don't remove those to take control?

This is a screenshot of a Mesa Biome using version: OreSpawn_1.10.2-1.1.0

http://i.imgur.com/k9KsrPo.png

And the config for vanilla ores is:

`{
	"dimensions":[
		{
			"dimension":"0",
			"ores":[
				{
					"blockID":"minecraft:coal_ore",
					"size":5,
					"variation":2,
					"frequency":6,
					"minHeight":0,
					"maxHeight":128,
					"biomes":[

					]
				},
				{
					"blockID":"minecraft:iron_ore",
					"size":2,
					"variation":2,
					"frequency":6,
					"minHeight":0,
					"maxHeight":64,
					"biomes":[

					]
				},
				{
					"blockID":"minecraft:gold_ore",
					"size":2,
					"variation":1,
					"frequency":2,
					"minHeight":0,
					"maxHeight":32,
					"biomes":[

					]
				},
				{
					"blockID":"minecraft:diamond_ore",
					"size":1,
					"variation":1,
					"frequency":2,
					"minHeight":0,
					"maxHeight":16,
					"biomes":[

					]
				},
				{
					"blockID":"minecraft:redstone_ore",
					"size":2,
					"variation":1,
					"frequency":2,
					"minHeight":0,
					"maxHeight":16,
					"biomes":[

					]
				},
				{
					"blockID":"minecraft:lapis_ore",
					"size":2,
					"variation":1,
					"frequency":4,
					"minHeight":0,
					"maxHeight":32,
					"biomes":[

					]
				},
				{
					"blockID":"minecraft:emerald_ore",
					"size":1,
					"variation":0,
					"frequency":1,
					"minHeight":4,
					"maxHeight":32,
					"biomes":[
					
					]
				},
				{
					"blockID":"minecraft:dirt",
					"size":50,
					"variation":25,
					"frequency":5,
					"minHeight":45,
					"maxHeight":255,
					"biomes":[

					]
				},
				{
					"blockID":"minecraft:gravel",
					"size":50,
					"variation":25,
					"frequency":4,
					"minHeight":45,
					"maxHeight":255,
					"biomes":[

					]
				},
				{
					"__comment":"granite",
					"blockID":"minecraft:stone",
					"blockMeta":1,
					"size":30,
					"variation":15,
					"frequency":5,
					"minHeight":55,
					"maxHeight":255,
					"biomes":[

					]
				},
				{
					"__comment":"diorite",
					"blockID":"minecraft:stone",
					"blockMeta":3,
					"size":30,
					"variation":15,
					"frequency":5,
					"minHeight":55,
					"maxHeight":255,
					"biomes":[

					]
				},
				{
					"__comment":"andesite",
					"blockID":"minecraft:stone",
					"blockMeta":5,
					"size":30,
					"variation":15,
					"frequency":5,
					"minHeight":55,
					"maxHeight":255,
					"biomes":[

					]
				}
			]
		},
		{
			"dimension":-1,
			"ores":[
				{
					"blockID":"minecraft:quartz_ore",
					"size":8,
					"variation":2,
					"frequency":4,
					"minHeight":0,
					"maxHeight":128,
					"biomes":[

					]
				}
			]
		}
	]
}
`

**Comment by dshadowwolf** [comment]
As far as I know, unless the "Replace Vanilla Oregen" option is turned on, no vanilla generation mechanic is overridden.

However... this is going onto the list of requested features as "allow specifying ores multiple times to account for differences in biome listings"

**Comment by dshadowwolf** [comment]
Alright - after opening the project to add this feature after the beta release was done, I find that it is already possible to specify different spawn rates and biomes for the same ore. All that is really stopping this request from being marked complete is the lack of ability to blacklist biomes - something that is in the design stage.

**Comment by dshadowwolf** [comment]
Ability to blacklist biomes is going to be in the next release - the code is in testing and being refined right now.

**Comment by dshadowwolf** [comment]
OreSpawn 3.1 is in the repo and in alpha testing - this brings whitelists and blacklists

**Comment by dshadowwolf** [comment]
@MrAmericanMike as with another issue that revolved around Biome issues, this should be solved in the current [1.11 work tree](/MinecraftModDevelopmentMods/OreSpawn/tree/master-1.11.2) and if you do not have the means to build the source tree yourself, you should be able to find a working late-alpha, early-beta of the current code on the [MMD Maven](https://maven.mcmoddev.com/com/mcmoddev/OreSpawn)

Please let us know if this resolves your issue.

**Comment by dshadowwolf** [comment]
This is possible in OreSpawn 3.1 and now 3.2 - closing this issue
