### ISSUE TITLE
guys what if suggestion:

### ISSUE THREAD

**Issue by dianamonde** [MinecraftModDevelopment/OreSpawn#194]

**Comment by dianamonde** [comment]
teh girlfriends should have a skin where they have no clothes on for the bikini version! also, they should add a different model for hyperrealistic feet! don't hate, its' just my opinion

**Comment by dshadowwolf** [comment]
fuck off - if you had half a brain you'd know this mod isn't the one you're talking about.

**Comment by jriwanek** [comment]
The girlfriend mod by theycallmedanger is long dead, will not be recieving updates and is *not* this mod.
