### ISSUE TITLE
 Problem with replacement system

### ISSUE THREAD

**Issue by javiburatos** [MinecraftModDevelopment/OreSpawn#196]
Hey, I have a problem with MMD Orespawn. i´m trying to generate diamonds in the moon (galacticraft mod) but i can't get it. Can anyone help me? I do a lot of test and I think that the problem is that i can't define the moon block correctly in the replacements file. Here I post my json files code
Orespawn:
{
    "version": "2.0",
    "spawns": {
                   "test": {
            "retrogen": false,
            "enabled": true,
            "feature": "default",
            "replaces": "Piedra",
            "dimensions": [
                -28
            ],
            "biomes": {
                "excludes": []
            },
            "parameters": {
                "size": 25,
                "variation": 12,
                "frequency": 20,
                "minHeight": 0,
                "maxHeight": 128
            },
            "blocks": [
                {
                    "name": "minecraft:diamond_ore",
                    "chance": 100
                }
            ]
        }
    }
}
{
   "default": 
    [
        { "name": "minecraft:stone" },
        { "name": "minecraft:andesite" },
        { "name": "minecraft:diorite" },
        { "name": "minecraft:granite" },
        { "name": "minecraft:netherrack" },
        { "name": "minecraft:end_stone" } 
    ],
    "Piedra": 
    [
        { "name": "galacticraftcore:basic_block_moon",
           "state": "basictypemoon=moon_stone" }
    ]
}

**Comment by dshadowwolf** [comment]
> "replaces": "Piedra",

I'd call this the issue, but it looks like you have it defined as a preset... Though I'm not 100% sure as you have everything all jammed together in the bug report and its impossible to tell what you have where.

**Comment by javiburatos** [comment]
One moment, I'm going to post the json files in pastebin.
https://pastebin.com/3PA2zDM3

**Comment by javiburatos** [comment]
I have also tried other configurations and none work. Here I post some configurations:
https://pastebin.com/uPzuucjA
