### ISSUE TITLE
[Suggestion] Allow Biome specification to be inverted to a blacklist

### ISSUE THREAD

**Issue by Dragnier** [MinecraftModDevelopment/OreSpawn#22]
I would like to have the ability to stop ores spawning in certain biomes specifically and it would be much easier to blacklist those rather than type out all of the ones I want the ore to actually spawn in.

**Comment by dshadowwolf** [comment]
Almost ready - should be in the next release (OreSpawn 3.1.0 - there are some major internal changes and the integration API has changed, as well as an update to "version 1.1" of the config format)

**Comment by dshadowwolf** [comment]
OreSpawn 3.1 is in the repo and in alpha testing - this update will close this issue.

**Comment by dshadowwolf** [comment]
Closing this as both blackilisting and whitelisting of biomes has been implemented.
