### ISSUE TITLE
Server crashes, saying that my file isn't a JSON object.

### ISSUE THREAD

**Issue by Ra-Zim** [MinecraftModDevelopment/OreSpawn#23]
I grabbed a .json file from this github for vanilla ores, made a couple of adjustments to the numbers, but otherwise nothing else was changed, and it is crashing my server.

Here's the crash report: http://pastebin.com/sRJagMvz

Here's the .json file: http://pastebin.com/gXwjh5mn

I currently have version 1.1.0 for MC 1.10.2

**Comment by dshadowwolf** [comment]
It isn't valid json

Valid JSON is enclosed in curly-braces { } - your file begins and ends with brackets - [ ]

**Comment by dshadowwolf** [comment]
you json is invalid

JSON files start with a curly brace - {   and end with its match - }
