### ISSUE TITLE
Underground Biomes Constructs 1.10 Compatibility

### ISSUE THREAD

**Issue by bookerthegeek** [MinecraftModDevelopment/OreSpawn#24]
Hello Good Sirs'!

I have a humble request, and that is when [UBC](https://github.com/Zeno410/UndergroundBiomesConstructs1.10) is installed you do your Java magic and have your* ores spawn in with the corresponding background for the UBC stone it is spawning in. Maybe @Zeno410 could shed some light on this as I can not find any info on how to do this other than the forum post [HERE](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293503-underground-biomes-constructs) But have no idea on how accurate it is as it points to the 1.7.10 branch of UBC

Thank you for taking the time to consider this request.

* Not your ores specifically, mainly the MMD family of ores.

**Comment by dshadowwolf** [comment]
#28

**Comment by dshadowwolf** [comment]
Basically... this ties in with the request for selecting what block is getting replaced.

Same answer there goes here: It's on the TODO of requests, but without any guarantees as to when or if it'll make a release

**Comment by dshadowwolf** [comment]
PR #38 (merged) currently makes it possible to specify the block to be replaced. As this seems to be the only thing that OreSpawn can do for UBC compat, this is being closed.
