### ISSUE TITLE
[Suggestion] Allow changing the replaced block when generating an ore

### ISSUE THREAD

**Issue by Lykrast** [MinecraftModDevelopment/OreSpawn#28]
This is probably harder to do than what I think but it would be really cool to have a (maybe optional) extra line for configuring ores to specify which block they'll replace when generating, instead of always stone/netherrack/end stone.

This could, for example, allow something like generating patches of coarse dirt in plains or to take care of ore generation in a dimension that doesn't use the vanilla stones (like how the Aether uses holystone).

**Comment by dshadowwolf** [comment]
This is something that we'll work on - for now the selection is somewhat limited and tied directly to the dimension - overworld types its "stone", nether it's "netherrack" and "The End" is "endstone"

At the moment we are hard at work on getting a port and rewrite of OreSpawn done that has a feature-parity with the current code but has the flexibility to have this request (and others) possible

**Comment by dshadowwolf** [comment]
Closing this, as PR #38 - which has been merged - gives a means to specify which block the ore can replace during generation
