### ISSUE TITLE
Request 1.11.2

### ISSUE THREAD

**Issue by MrSapient** [MinecraftModDevelopment/OreSpawn#29]
I'm currently working on a modpack and this mod was recommended to me by darkosto as a mod he has used before to control ore spawning. I would like to be able to use it in my pack in 1.11.2. However its not been updated since dec 2016. I'm in no way asking for a release date or trying to rush anyone just simplifying trying to find out if its still actively developed.

**Comment by jriwanek** [comment]
OS3 will be released for 1.11.2 soon.
