### ISSUE TITLE
Does not have built-in .json files for Base/Modern/Nether/End Metals mods

### ISSUE THREAD

**Issue by majix560** [MinecraftModDevelopment/OreSpawn#3]
Since the name change, MMD Ore Spawn does not generate default orespawn json files for the Base Metals, Modern Metals, Nether Metals, and End Metals mods.
Every ore from those mods generate in the overworld, including the ones from Nether Metals and End Metals.
Here's the console log.
http://pastebin.com/RwfGEkJM

**Comment by knoxhack** [comment]
Use version OreSpawn_1.10.2-1.1.0

**Comment by knoxhack** [comment]
You guys should pull those broken versions from Curse.

**Comment by iLexiconn** [comment]
There's a reason they're marked as alpha...

**Comment by iLexiconn** [comment]
And the fact that they don't generate JSON files isn't OreSpawn's fault, 1.x.x didn't have a system for that. Mods handled that themselves.
