### ISSUE TITLE
[1.11.2] OreSpawn doesnt generate anything

### ISSUE THREAD

**Issue by vico93** [MinecraftModDevelopment/OreSpawn#31]
Well, i dont know if the mod was abandoned, but anyway, dropping my issue here.

I built OreSpawn from source for 1.11.2, and after trying to add [this json](https://github.com/vicocraft/coopermod/blob/master/orespawn/coopermod.json) (plus the default orespawn.json) doesnt generate any ore in the world, both vanilla and the mod block.

![image](https://cloud.githubusercontent.com/assets/3485505/26775011/62f5cb00-49a9-11e7-835e-e5895aafbb19.png)

For reference, i'm using Forge 13.20.0.2313 and this mod block is from a [CustomStuff 4](https://github.com/cubex2/customstuff4)'s submod. I also use Jared's Crafttweaker and this one recognizes the block and register recipes with that, so i think it isnt a problem with my block.

Plus i searched for the logs and didnt find any error line related to OreSpawn or CS4.

Thanks in advance!

**Comment by dshadowwolf** [comment]
OreSpawn for 1.11 is currently highly broken and in the process of being worked on. Thank you for the report, though, as I had been unaware that any work was underway or that it needed to be looked at.

**Comment by jriwanek** [comment]
Should be fixed in the upcoming 3.x release
