### ISSUE TITLE
Question regarding 1.11.2 console message spam

### ISSUE THREAD

**Issue by MCJediYoda** [MinecraftModDevelopment/OreSpawn#45]
I am seeing a ton of these messages in the console.
[11:54:21] [Server thread/FATAL] [orespawn]: no spawn entries for dimension -51 or for all dimensions
I dont want any ores to spawn in dimension -51 (Cavern ruins dimension).  

Can I disable this message somehow?  Without making a orespawn.json entry for dimension -51?

Forge 13.20.0.2366
OreSpawn-1.11.2-3.0.0.36

Thanks

**Comment by dshadowwolf** [comment]
Not at current - we're working on a new release that should solve this - right now OreSpawn will carp if its asked to do work on a dimension that it doesn't have any settings for (like is showing here). This will be silenced in the next release (which will also include Biome Dictionary support, Biome Blacklisting and is planned to also allow for multiple ores in the same spawn entry).

**Comment by MCJediYoda** [comment]
Thank you

**Comment by dshadowwolf** [comment]
Need to make another couple passes, but I think I've found all the debugging code I stuck in to find and fix issues.

**Comment by dshadowwolf** [comment]
Okay - OreSpawn 3.1 with all of its new features (and hopefully none of the debugging outputs) is about ready - the release is up to @jriwanek who acts as a coordinator and release manager for several MMD projects.

**Comment by dshadowwolf** [comment]
All extra debugging output has, if memory serves, been removed and OreSpawn is no longer spamming the logs badly. Issue closed.
