### ISSUE TITLE
1.10 version is overwritting changes made to config files

### ISSUE THREAD

**Issue by Zygus42** [MinecraftModDevelopment/OreSpawn#5]
This "feature" makes it completely useless as a mod.  I'm guessing it has something to do with the config folder now residing in the main dir instead of the config dir.

**Comment by Zygus42** [comment]
This is for version 2.0.0.4

**Comment by iLexiconn** [comment]
Thanks for the report, I'll look into it

**Comment by Syndaryl** [comment]
It's persistently removing the dimension tag from every .json except orespawn.json and minecraft.json too - so all the Nether Ores are spawning all over the place.

**Comment by iLexiconn** [comment]
That makes no sense...

**Comment by Sevidra** [comment]
I can verify that as of the latest version today, this is still happening.  There are no Dimension tags in Nether Metals or Netherrocks orespawn filed, nothing in End Metals either - so all those ores are spawning in the overworld.

Further, if I try to overwrite to increase or decrease the amount/rarity of any ore, it just gets overwritten as soon as I load the game and/or server (I've done both).

**Comment by mrtopf** [comment]
So one report from what I just experienced: I changed `basemetals.js` and `modernmetals.json`. my changes to basemetals stayed but modernmetals was overwritten every time (e.g. I deleted all ores in the list or changed size=0).

**Comment by iLexiconn** [comment]
Did the old config still exist?

**Comment by mrtopf** [comment]
what do you mean by old config? I used the generated `modernmetals.json`, removed the ores in there (as for now I didn't want them in the world for easier testing of basemetals). After starting the game again the original files with the ores was back. 

So it's all about that one file in `orespan/modernmetals.json` and my changes were gone. I can try that again the next days when I am home again.

**Comment by mrtopf** [comment]
and not sure how I unassigned you, btw.

**Comment by iLexiconn** [comment]
I think it converts the old one and overwrites the new one. Try moving the old config to a different place once it's converted.

You didn't unassign me, I left the repo so I can't be assigned anymore. I guess it's a bug that it's showing that you did.

**Comment by Sevidra** [comment]
I have no idea about old config - I installed fresh on a new server with no old files and it did that to the only config files I found. ?

**Comment by iLexiconn** [comment]
https://minecraft.curseforge.com/projects/mmd-orespawn/files/2345032
