### ISSUE TITLE
[CTD] Ticking crash when going to Nether

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopment/OreSpawn#57]
[crash-2017-07-14_22.28.20-server.txt](https://github.com/MinecraftModDevelopmentMods/OreSpawn/files/1150075/crash-2017-07-14_22.28.20-server.txt)
[crash-2017-07-14_22.44.55-server.txt](https://github.com/MinecraftModDevelopmentMods/OreSpawn/files/1150076/crash-2017-07-14_22.44.55-server.txt)
[crash-2017-07-15_00.38.24-server.txt](https://github.com/MinecraftModDevelopmentMods/OreSpawn/files/1150081/crash-2017-07-15_00.38.24-server.txt)

Don't know why, but Orespawn is the last(first) called in crashes

**Comment by dshadowwolf** [comment]
Let me get things setup to recreate and see if I can trigger it with just OreSpawn in its most recent version (it should be getting released by the nineteenth alongside a second beta for the various *metals mods)

Note that where the crash occurs its actually looking up cached spawn data - it caches any ores that are set to spawn outside the currently loaded chunk set (to stop "cascading chunk gen lag") - on a first visit to the Nether this should be empty and nothing should happen, but if you've done a lot of travel and haven't given the gen time enough to settle, the cache might get large... It might be best if there is some control put in place there - let me talk with @jriwanek and the rest of the team about this.

**Comment by drakray** [comment]
in the last crashLog, it happened in a New World, Creative, all default, built a Portal near spawn, crash on Nether loading
 first crash is in a world I played a lot, explored the overworld around my base, made a NPortal, crashed on loading too(world is unusable for now, as in second cLog, I crash on world loading, since my char is "between world")

**Comment by drakray** [comment]
got a lot of mod installed, like BoP, Galacticraft, FunOre, Mekanism, to name a couple

**Comment by drakray** [comment]
[My full instance](https://www.dropbox.com/s/pkogpoyd36i30j1/1112M.zip?dl=0) with saves
With Forge 1.11.2-2393

**Comment by dshadowwolf** [comment]
Have not been able to get your setup to run - even when dedicating 4G of RAM to MC and running it on the fastest machine I have it has either crashed or hung during first-run.

I am still trying, however... At this point, though, I'm starting to think this might have causes outside OS3 and the OS3 cache-check was just the last tiny bit needed to trigger it. I'm not writing it off - just a bit peeved that I've been unable to replicate as yet.

**Comment by drakray** [comment]
I give 6go in MCLauncher.
I tried removing BoP or Galacticraft(and addons), but I still got the crash

**Comment by dshadowwolf** [comment]
Alright, found what might be the issue - seems that Java, in certain situations, might be trying to access the cache even if its completely empty, causing it to try and de-reference the data in it despite it being null. I've added a guard condition as well as a check elsewhere that is, surprisingly, missing that is supposed to guard for a specific config condition. Going to test soon.

**Comment by dshadowwolf** [comment]
And thank you for this - you've helped find a number of small edge-case bugs so far that I'm in the process of fixing. I've got the original bug fixed and that has shown an additional one where we've got the wrong values going into place in some other bits.

**Comment by drakray** [comment]
No problem, as long as by the end I can get back in my saves lol ;)

**Comment by dshadowwolf** [comment]
Well... it looks like there might be an issue with that - apparently (right now) the parameters for the spawns seem to not be getting set at all.

I'm looking into that now :)

**Comment by dshadowwolf** [comment]
Found it... I'm going to be pushing a fix for the one edge-case and the one "The programmer was an idiot" case you turned up (I was doing some de-duplication and accidentally deleted something that was necessary) - beyond that, you'll want to replace any instance of "min_height" with "minHeight" in the configs - I found 2 instances of it (only) in the basemetals config

**Comment by drakray** [comment]
My bad, I thought I repaired them all when I tweaked my config
Will the fix be pushed on Curse, or are you waiting for more fix?

**Comment by dshadowwolf** [comment]
Hopefully

@jriwanek is in charge of Curse releases - though I have recommended this already
