### ISSUE TITLE
[Question]How to add a ore with meta ID ?

### ISSUE THREAD

**Issue by TehporP** [MinecraftModDevelopment/OreSpawn#59]
I wanna add IC2 copper ore in the world though the orespawn   ex. (ic2:resource:1)
How should I write the json script?

**Comment by dshadowwolf** [comment]
Hrm... I need to double-check, but I thought I'd left the "metadata" parameter in the json format, even up to the current version of the v3 setup.

**Comment by TehporP** [comment]
https://pastebin.com/8Wd4xZAH

Like this one?

**Comment by dshadowwolf** [comment]
Feeling a bit better than I have and it looks like you've found a slight logic flaw in the v3 code, sadly...

It seems like you'll need to use a v2 format file while I work on fixing a stupid mistake I made... seems the state handling helper, which should have also covered metadata, does not.

**Comment by Thyriel** [comment]
@dshadowwolf did you fix that yet and if yes how is the correct v3 code for metadata looking like ?
I've tried this in 3.1.0.8 but MC just freezes then and removes the whole ore entry i made from orespawn.json (copper Ore is "forestry:resources:1"):

"block": "forestry:resources",
"state": "metadata\u003d1",
...

(also tried meta and variant instead metadata). JSON seems beside that to be correct as it's spawning forestry:resources:0 ore when i don't have the "state" line in the code

**Comment by dshadowwolf** [comment]
yeah, for metadata itself... try using "metaData" and not "state" - I did keep support for it in v3. That is in the current version for 1.12 and if it isn't in the 1.11 version, I can easily push a new release there.

**Comment by Thyriel** [comment]
That works great thanks :)
(Maybe add one example of that to the default file for easier Howto ?)

**Comment by dshadowwolf** [comment]
...truthfully the docs need a complete overhaul - I've just been doing a bit of the "run around like a chicken with its head cut off" thing trying to fix bugs and keep the 7 mods I have coding duties for functional and working with the latest MC versions. Not to mention the two mods I've been trying to get going and maybe released for about 9 months now... Know anyone that would be interested in writing up some documentation ?

**Comment by jriwanek** [comment]
> {
>  "version": "2.0",
>  "spawns": {
>    "chisel-basalt2-7": {
>      "blocks": [ { "name": "chisel:basalt2", "state": "variation=7", "chance": 33 },
>                  { "name": "chisel:limestone2", "state": "variation=7", "chance": 33 },
>                  { "name": "chisel:marble2", "state": "variation=7", "chance": 34 } ],
>      "biomes": { "excludes": ["minecraft:desert"] },
>      "dimensions": [0],
>      "parameters": {
>           "maxHeight": 256,
>           "minHeight": 0,
>           "frequency": 100.0,
>           "size": 256,
>           "variation": 16
>      },
>      "feature": "default",
>      "replaces": "minecraft:stone",
>      "enabled": true,
>      "retrogen": false
>    }
>  }
>}

**Comment by jriwanek** [comment]
It's a bit flat, but it's a start.
