### ISSUE TITLE
Does this officially support 1.12.2 because I noticed curse only says 1.12

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MinecraftModDevelopment/OreSpawn#67]
Hey I noticed you set it as only being able to working on 1.12 has that changed?

**Comment by dshadowwolf** [comment]
It has not, officially, been tested with 1.12.2 - only 1.12 and 1.12.1 - but... the 3.1 series - ie: the current code - should work on 1.12.2

1.12.2 is too recent for me, in my state of trying to get the mods I have some responsibility for, ported to at least 1.12.1 - Base Metals alone has been more than a weeks worth of work, so far

**Comment by P3rf3ctXZer0** [comment]
Do you want me to test it anyways and report bugs?

**Comment by dshadowwolf** [comment]
That would be wonderful!  We've had people coming to us on GitHub and helping with Base Metals and Modern Metals, so your help would be appreciated!
