### ISSUE TITLE
[1.10.2] Ore Spawn cause exception error crash

### ISSUE THREAD

**Issue by llloyd4** [MinecraftModDevelopment/OreSpawn#68]
Went to start up Minecraft and it crashed back to the desktop, error report says Orespawn caused an exception error. This is 1.10.2-1.1.0 version of Orespawn.

Crash Report: https://pastebin.com/DuRNtrhJ

Config .json file : 

{
     "dimension": "+",
     "ores": [
        {
        "block": "thermalfoundation:ore",
	"meta": 6, 
        "size": 4,
        "variation": 4,
        "frequency": 1,
        "min_height": 5,
        "max_height": 35
      }
  ]
 }

**Comment by dshadowwolf** [comment]
Malformed JSON for 1.1.0 - assistance and correct format example given on MMD Discord.
