### ISSUE TITLE
[Question] max size / variation ?

### ISSUE THREAD

**Issue by Thyriel** [MinecraftModDevelopment/OreSpawn#69]
I'm currently trying to generate "as large as possible" but rare veins, but seems when i set size and/or variation too high nothing is generated at all.
So what's the maximum accepted values for these ?

And i guess there's no way to use other kind vein shapes then sphere or ?

**Comment by Thyriel** [comment]
Ups my fault. I accidentally deleted the comma after the numbers which was causing the no spawn problem.
Seems incredible high numers even work, although it's taking ages then to load

**Comment by dshadowwolf** [comment]
yeah - some of the numbers are used in a loop, which will cause the amount of time spent in the "Chunk Decoration" phase of world generation to skyrocket. I've thought about implementing limits, but backwards compatibility with the older OreSpawn 1 and 2 configs and how those two worked stop me from doing such at this time.
