### ISSUE TITLE
Make Clusters / Veins to have maximum flexibility.

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopment/OreSpawn#80]
I'll just make you an example for what i would be able to specify with Maximum Flexibility:

Generate 1 - 2 Clusters / Veins consisting of 4-8 blocks of silver and 20 - 24 blocks of lead.
This example might be called galena internally.

It will get much more imminent if you say - this is ficitional - there is a Mineral called "Muchium"

It generates 1 - 2 Clusters with clusters consisting of 1-2 blocks Gold, 2-5 blocks copper, 6-7 blocks iron and 2-4 blocks lead. That will be hard to achieve if you can't specifiy a block number.

**Comment by dshadowwolf** [comment]
No good ideas on how to make this work and not require a lot of internal changes

**Comment by D3nnis3n** [comment]
This is still relevant for a future upate, as as of now there is no possibility to define exactly the amount of ores for multi-ore spawns. Might be a Feature only for the precision Generator.

**Comment by dshadowwolf** [comment]
Exactly what I was getting at - the existing code is designed to take a probability value (an X in Y chance, where Y is the total of all the X's specified) and isn't, really, all that precise on it. I do, however, have an idea of how to make this work, it just requires providing an alternate structure to the ore-list build... which would then be possible to apply to all the spawners. Its just a rather big change.

**Comment by Insane96** [comment]
This is actually now possible with the `blocks` field

```
			"blocks": [
				{
					"name": "minecraft:coal_ore",
					"chance": 90
				},
				{
					"name": "minecraft:iron_ore",
					"chance": 10
				}
			]
```

**Comment by D3nnis3n** [comment]
Well, this does not allow me to define an near exact amount or an near exact range of blocks, afaik.

**Comment by Insane96** [comment]
Uhm yeah, you can only specify chances

**Comment by D3nnis3n** [comment]
Exactly. And my proposal is for the precision generator, that allows "more flexibility" *g*

**Comment by dshadowwolf** [comment]
The "chance" is as precise as I can make it without involving all kinds of extra math and bookkeeping that would slow everything down badly

**Comment by dshadowwolf** [comment]
and there is a "precision" generator that generates a block of ore of a specified size to within +/- 5% (I've tried for better, but could not make it happen)

**Comment by D3nnis3n** [comment]
Yes, the missing thing from this suggestion after the creation of the precision generator was, that the precisison generator is missing a feature, that allows to make the multi-ore spawns to also happen in range within +/- 5%. At the moment this is only possible for spawns with only one ore.

**Comment by dshadowwolf** [comment]
@D3nnis3n yeah - as I said above... I've made the "chance" as precise as possible without causing bad world-gen lag. I could do it a lot more precise, but that has trade-offs. As it is, the chance selection actually lays out a flattened segment-tree for making the selection... it should even adjust it after each spawn, but I might have messed up that part - or forgotten to include it.

**Comment by dshadowwolf** [comment]
with the "precision" generator available and the requested precision here not being fully possible... closing this issue as resolved/not an issue
