### ISSUE TITLE
Crash with forge-1.12.2-14.23.0.2512-universal on Dedicated Server

### ISSUE THREAD

**Issue by YaibaToKen** [MinecraftModDevelopment/OreSpawn#84]
Reported this at [SlimeKnights/Mantle](https://github.com/SlimeKnights/Mantle/issues/98) and was told this is most likely coming from  your end. Any other info you might need, I'll be happy to provide.

[crash-2017-10-14_22.29.03-server.txt](https://github.com/MinecraftModDevelopmentMods/OreSpawn/files/1385346/crash-2017-10-14_22.29.03-server.txt)

**Comment by dshadowwolf** [comment]
Known issue, fixed in an upcoming release - you can try the versions at https://maven.mcmoddev.com/ under "com.mcmoddev.basemetals"
