### ISSUE TITLE
Collection Issue

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopment/OreSpawn#90]
- [x] Exclude and Include for Dimension
- [x] Variance for "attempts" (Like length min max, attempts min max)
- [x] Flat Bedrock with configurable Level of bedrock
- [x] Better Logging - give warnings and success notices for every ore
- [x] Skip wrong ore Generation entries (Checkin Gold - valid - spawned, checking iron - invalid - skipped)
- [x] Move presets to a file in syconfig for deduplication
- [x] Check if retrogen works
- [x] Make exact block Count for each ore in multi-ore spawns possible
- [x] Give Clusters the ability to define a exact block Count like in normal-Cloud and veins.
- [x] Variable Consistency: https://github.com/MinecraftModDevelopmentMods/OreSpawn/issues/86
- [ ] Make Clusters / Veins to have maximum flexibility. : https://github.com/MinecraftModDevelopmentMods/OreSpawn/issues/86

**Comment by jriwanek** [comment]
Not sure #86 is a good idea personally, we've already had a ton of flux on the names, continuously changing them is just going to put people off, so if we are going to do it, then the old names should be aliased to the new ones.

**Comment by D3nnis3n** [comment]
As this is a completley new Major Version i think if there is a time to Change this, then it’s now. He also already changed the variable names for the Default Generator (are not the same as before). He just missed doing this for the other ones, too. I suggested to use easier to rembember names. And this was what i got up with. So you either should not Change it at all, or make it the same everywhere.

**Comment by dshadowwolf** [comment]
tentatively flagging the include/exclude as done - needs testing but it has been coded. 10-NOV-2017 will see an attempt made at the other two items.

**Comment by dshadowwolf** [comment]
```json
"attempts": {
  "minimum": 4,
  "maximum": 8
}
```
Is now supported in place of the old version for all feature-generators that supported "attempts" as a parameter. That means "clusters", "normal-cloud" and "vein". The Default Generator only ever made a single attempt (if that) and "precision" is designed with trying to reach as close to the +/- 15% of configured goal as possible - using a variable number of attempts to spawn per node would break this design.

Should be "build 94" (3.2.0.94) when it hits the maven here in a bit.

**Comment by D3nnis3n** [comment]
Closed as of everything but a seperate issue done.
