### ISSUE TITLE
Normal Cloud Generator does not work at all

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopment/OreSpawn#95]
My config:

>         "uranium-92": {
>             "biomes": { 
>                 "excludes": [ ] 
>             },
>             "blocks": [
>                 { 
>                     "chance": 100,
>                     "name": "modernmetals:uranium_ore"
>                 }
>             ],
>             "dimensions":  [ 0 ],
>             "enabled": true,
>             "feature": "normal-cloud",
>             "replaces": "minecraft:stone",
>             "retrogen": false,
>             "parameters": {
>                 "attempts": 4,
>                 "frequency": 100,
>                 "maxSpread" 3,
>                 "maxHeight": 48,
>                 "minHeight": 32,
>                 "medianSize": 13,
>                 "variation": 0
>             }
>         },

Result: No ores spawned.

**Comment by dshadowwolf** [comment]
you told it to spawn a variant of the ore that doesn't exist, so when it got back a null, it discarded the spawn

**Comment by dshadowwolf** [comment]
Work has been done - does the latest Maven code have this fixed ?

**Comment by dshadowwolf** [comment]
Testing shows normal-cloud functional - closing
